Ruby: include/ruby/internal/core/robject.h File Reference
robject.h File Reference
(549e9383e46d9fb9074cef483caaf9b5af908199)
Defines struct RObject.
#include "ruby/internal/config.h"
#include "ruby/internal/attr/artificial.h"
#include "ruby/internal/attr/deprecated.h"
#include "ruby/internal/attr/pure.h"
#include "ruby/internal/cast.h"
#include "ruby/internal/fl_type.h"
#include "ruby/internal/value.h"
#include "ruby/internal/value_type.h"
Data Structures
struct RObject
Ruby's ordinal objects.
Macros
#define ROBJECT(obj) RBIMPL_CAST((struct RObject *)(obj))
Convenient casting macro.
Enumerations
enum ruby_robject_consts {
ROBJECT_EMBED_LEN_MAX = ((int)(sizeof(VALUE[RVALUE_EMBED_LEN_MAX]) / sizeof(VALUE))) , ROBJECT_EMBED_LEN_MAX = ((int)(sizeof(VALUE[RVALUE_EMBED_LEN_MAX]) / (sizeof(VALUE)))) , ROBJECT_EMBED_LEN_MAX = ((int)(sizeof(VALUE[3]) / (sizeof(VALUE)))) , ROBJECT_EMBED_LEN_MAX = ((int)(sizeof(VALUE[3]) / (sizeof(VALUE)))) ,
ROBJECT_EMBED_LEN_MAX = ((int)(sizeof(VALUE[3]) / (sizeof(VALUE)))) , ROBJECT_EMBED_LEN_MAX = RBIMPL_EMBED_LEN_MAX_OF(VALUE)
}
This is an enum because GDB wants it (rather than a macro).
Functions
static uint32_t ROBJECT_NUMIV (VALUE obj)
Queries the number of instance variables.
static VALUE * ROBJECT_IVPTR (VALUE obj)
Queries the instance variables.
Detailed Description
Defines struct RObject.
Author
Ruby developers ruby-.nosp@m.core.nosp@m.@ruby.nosp@m.-lan.nosp@m.g.org
Copyright
This file is a part of the programming language Ruby. Permission is hereby granted, to either redistribute and/or modify this file, provided that the conditions mentioned in the file COPYING are met. Consult the file for details.
Warning
Symbols prefixed with either RBIMPL or rbimpl are implementation details. Don't take them as canon. They could rapidly appear then vanish. The name (path) of this header file is also an implementation detail. Do not expect it to persist at the place it is now. Developers are free to move it anywhere anytime at will.
Note
To ruby-core: remember that this header can be possibly recursively included from extension libraries written in C++. Do not expect for instance __VA_ARGS__ is always available. We assume C99 for ruby itself but we don't assume languages of extension libraries. They could be written in C++98.
Definition in file robject.h.
Macro Definition Documentation
ROBJECT
#define ROBJECT (obj) RBIMPL_CAST((struct RObject *)(obj))
Convenient casting macro.
Parameters
obj An object, which is in fact an RRegexp.
Returns
The passed object casted to RRegexp.
Definition at line 43 of file robject.h.
Enumeration Type Documentation
ruby_robject_consts
enum ruby_robject_consts
This is an enum because GDB wants it (rather than a macro).
People need not bother.
Enumerator
ROBJECT_EMBED_LEN_MAX
Max possible number of instance variables that can be embedded.
Definition at line 82 of file robject.h.
Function Documentation
ROBJECT_IVPTR()
static VALUE * ROBJECT_IVPTR (VALUE obj) inline static
Queries the instance variables.
Parameters
[in] obj Object in question.
Returns
Its instance variables, in C array.
Precondition
obj must be an instance of RObject.
Definition at line 171 of file robject.h.
Referenced by rb_ivar_count(), and rb_ivar_defined().
ROBJECT_NUMIV()
static uint32_t ROBJECT_NUMIV (VALUE obj) inline static
Queries the number of instance variables.
Parameters
[in] obj Object in question.
Returns
Its number of instance variables.
Precondition
obj must be an instance of RObject.
Definition at line 145 of file robject.h.
Referenced by rb_ivar_count(), and rb_ivar_defined().